// GENERATED FILE — do not edit.
// Source of truth: constituency/pc_name_registry.py (per-seat verification
// comments live there; see DATA_CLAIMS.md CLAIM-2026-0036).
// Regenerate: python3 scripts/gen_pc_name_registry.py

/** State-scoped PC-name variants -> canonical 2024 seat name. */
export const PC_NAME_REGISTRY: Record<string, Record<string, string>> = {
  "ANDAMAN AND NICOBAR": {
    "ANDAMAN AND NICOBAR ISLANDS": "ANDAMAN & NICOBAR ISLANDS",
  },
  "ANDHRA PRADESH": {
    "ANANTHAPUR": "ANANTAPUR",
    "KURNOOLU": "KURNOOL",
    "NARSARAOPET": "NARASARAOPET",
    "THIRUPATHI(SC)": "TIRUPATI (SC)",
  },
  "ASSAM": {
    "AUTONOMOUS DISTRICT": "DIPHU",
    "GAUHATI": "GUWAHATI",
    "KALIABOR": "KAZIRANGA",
    "MANGALDOI": "DARRANG-UDALGURI",
    "NOWGONG": "NAGAON",
    "TEZPUR": "SONITPUR",
  },
  "BIHAR": {
    "PATLIPUTRA": "PATALIPUTRA",
  },
  "CHHATTISGARH": {
    "JANJGIR-CHAMPA (SC": "JANJGIR-CHAMPA (SC)",
  },
  "DADRA AND NAGAR HAVELI AND DAMAN AND DIU": {
    "DADAR & NAGAR HAVELI": "DADRA & NAGAR HAVELI",
    "DADRA AND NAGAR HAVELI": "DADRA & NAGAR HAVELI",
  },
  "DELHI": {
    "NORTH-EAST DELHI": "NORTH EAST DELHI",
    "NORTH-WEST DELHI": "NORTH WEST DELHI",
  },
  "JAMMU AND KASHMIR": {
    "ANANTANAG": "ANANTNAG-RAJOURI",
  },
  "JHARKHAND": {
    "PALAMAU": "PALAMU",
  },
  "KERALA": {
    "THIRUVANANTHAPURA": "THIRUVANANTHAPURAM",
  },
  "MAHARASHTRA": {
    "BHANDARA GONDIYA": "BHANDARA-GONDIYA",
    "GADCHIROLI - CHIMUR": "GADCHIROLI-CHIMUR",
    "HATKANANGALE": "HATKANANGLE",
    "MUMBAI NORTH-CENTRAL": "MUMBAI NORTH CENTRAL",
    "MUMBAI NORTH-EAST": "MUMBAI NORTH EAST",
    "MUMBAI NORTH-WEST": "MUMBAI NORTH WEST",
    "MUMBAI SOUTH -CENTRA": "MUMBAI SOUTH CENTRAL",
    "RATNAGIRI ?SINDHUDUR": "RATNAGIRI-SINDHUDURG",
    "RATNAGIRI- SINDHUDURG": "RATNAGIRI-SINDHUDURG",
    "YAVATMAL- WASHIM": "YAVATMAL-WASHIM",
  },
  "PUDUCHERRY": {
    "PONDICHERRY": "PUDUCHERRY",
  },
  "PUNJAB": {
    "FATEHGARH SAHIB (SC": "FATEHGARH SAHIB (SC)",
  },
  "RAJASTHAN": {
    "KARAULI ?DHOLPUR(SC)": "KARAULI-DHOLPUR (SC)",
    "TONK ? SAWAI MADHOPUR": "TONK-SAWAI MADHOPUR",
  },
  "UTTAR PRADESH": {
    "BAHARAICH": "BAHRAICH",
  },
  "UTTARAKHAND": {
    "HARDWAR": "HARIDWAR",
    "NAINITAL-UDHAMSINGH NAG": "NAINITAL-UDHAMSINGH NAGAR",
  },
  "WEST BENGAL": {
    "ARAMBAG": "ARAMBAGH",
    "JOYNAGAR": "JAYNAGAR",
    "SERAMPORE": "SREERAMPUR",
    "SRERAMPUR": "SREERAMPUR",
  },
};
