"""Normalize district names to canonical form across all data sources.

Government portals, India Post, and census boundaries each spell district
names differently ("VILLUPPURAM"/"VILUPPURAM", "MYSORE"/"MYSURU",
"24 PARAGANAS NORTH"/"NORTH 24 PARGANAS"). Every table keyed by
(state, district) must pass through normalize_district() at load time or
cross-scheme joins silently fragment.

Alias registry: db/district_aliases.py (generated by
scripts/gen_district_aliases.py — edit _OVERRIDES there).
"""

from __future__ import annotations

import re
import sqlite3

from db.district_aliases import ALIASES
from db.normalize_states import normalize_state


def normalize_district(name: str, state: str = "") -> str:
    """Canonical district name: mechanical cleanup + state-scoped alias lookup.

    `state` should already be canonical (see normalize_states). Returns the
    mechanically-cleaned name unchanged when no alias exists. 'ALL'
    (state-level rows) passes through untouched.
    """
    s = str(name).upper().strip()
    if s == "ALL":
        return s
    s = s.replace("-", " ").replace("_", " ").replace(".", " ")
    s = re.sub(r"[()]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return ALIASES.get((state, s), s)


def normalize_records(
    records: list[dict],
    district_field: str = "district",
    state_field: str = "state",
) -> list[dict]:
    """Return records with canonical district names (no-op if field absent)."""
    out = []
    for r in records:
        if district_field in r and r.get(district_field) is not None:
            r = {
                **r,
                district_field: normalize_district(
                    r[district_field], r.get(state_field, "")
                ),
            }
        out.append(r)
    return out


def normalize_civic_tables(conn: sqlite3.Connection) -> dict[str, int]:
    """Normalize state+district in the civic tables loaded outside run_all
    (PIN directory, constituency maps). Idempotent; safe to run every load.

    Uses UPDATE OR REPLACE so rows that collide after normalization
    (two spellings of one district) merge instead of erroring.
    """
    changed: dict[str, int] = {}

    junk = conn.execute(
        "DELETE FROM pin_district_mapping WHERE district = 'NA' OR state = 'NA'"
    ).rowcount
    if junk:
        changed["pin_district_mapping (junk rows removed)"] = junk

    for table in ("pin_district_mapping", "constituency_district", "ac_district"):
        rows = conn.execute(
            f"SELECT rowid, state, district FROM {table}"
        ).fetchall()
        n = 0
        for rowid, state, district in rows:
            st = normalize_state(state)
            d = normalize_district(district, st)
            if st != state or d != district:
                conn.execute(
                    f"UPDATE OR REPLACE {table} SET state = ?, district = ? WHERE rowid = ?",
                    (st, d, rowid),
                )
                n += 1
        if n:
            changed[table] = n

    # district_lineage keys by (new_district, state) and references a parent
    # district — both sides must speak canonical names.
    rows = conn.execute(
        "SELECT rowid, state, new_district, parent_district FROM district_lineage"
    ).fetchall()
    n = 0
    for rowid, state, new_d, parent_d in rows:
        st = normalize_state(state)
        nd = normalize_district(new_d, st)
        pd = normalize_district(parent_d, st)
        if st != state or nd != new_d or pd != parent_d:
            conn.execute(
                "UPDATE OR REPLACE district_lineage"
                " SET state = ?, new_district = ?, parent_district = ? WHERE rowid = ?",
                (st, nd, pd, rowid),
            )
            n += 1
    if n:
        changed["district_lineage"] = n

    conn.commit()
    return changed
